# Generated by Django 5.1.3 on 2024-12-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_moduleprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprogress',
            name='total_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
